### PR TITLE
Issue-4356: Add Code Linter To utopia-php/websocket

### PR DESCRIPTION
**Pull request by Rutam21**
## What

This PR aims to resolve the issue https://github.com/appwrite/appwrite/issues/4356.

## How

- Code Linter has been added to utopia-php/websocket repository.
- All existing files are formatted as per the Linting rules.
- PR Template has been followed as mentioned in https://github.com/utopia-php/ab/pull/7.

Fixes https://github.com/appwrite/appwrite/issues/4356

### CODE REVIEW

**Comment by Rutam21** [comment]
@Meldiron Please review and suggest changes, if any. Thanks.

cc: @stnguyen90 @christyjacob4

**Comment by PineappleIOnic** [comment]
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

**Review by stnguyen90 — CHANGES_REQUESTED** [review]
Great PR! 🤯 Looks like there are merge conflicts now. Would you please

**Comment by christyjacob4** [comment]
@Rutam21 thanks a lot for your contributions during Hacktoberfest 2022! 

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.

**Review by christyjacob4 — APPROVED** [review]

**Pull request merged**
